"""
Canonical Opponents for Active Inference Experiments
============================================================

Authors: Hanchen Wang
Date: 2026-06

Purpose
-------
This file provides a collection of benchmark opponents for evaluating
Active Inference agents in repeated games (e.g. Prisoner's Dilemma, Chicken).

Design Philosophy
-----------------
The opponents are intentionally simple and interpretable. Each strategy
represents a different hypothesis about how an opponent might behave.

Researchers can use these opponents to test:

1. State inference
   - Can the AIF agent infer hidden states correctly?

2. Transition-model learning
   - Can the AIF agent recover TFT, Grim, Pavlov, etc.?

3. Bayesian Model Reduction (BMR)
   - Does evidence accumulate for the correct behavioural model?

4. Adaptation
   - Can the AIF agent respond appropriately to changing opponents?

Implemented Strategies
----------------------
Cooperator      : Always cooperate.
Defector        : Always defect.
TFT             : Tit-for-Tat.
StochasticTFT   : Noisy probabilistic TFT.
Grim            : Canonical Grim Trigger.
ThresholdGrim   : Grim after N defections.
Pavlov          : Win-Stay Lose-Shift.
Mixed           : Random mixed strategy.
HiddenState     : Behaviour generated by latent Markov state.

Extension Guide
---------------
To add a new strategy:

1. Add action logic inside select_action().
2. Add any memory updates inside infer_state().
3. Optionally expose hidden state through
   get_ground_truth_state().

This structure keeps all strategies consistent with the simulator API.
"""

import torch
import random


class DummyAgent:
    """
    Benchmark opponent implementing several canonical game-theoretic strategies.

    The class exposes the same interface as the Active Inference agent:
        infer_state()
        select_action()
        learn()

    This allows the simulator to treat both agent types identically.
    """

    def __init__(
        self,
        id,
        strategy,
        game_matrix=None,
        num_states=2,
        noise=0.0,
        reward_threshold=None,
        grim_threshold=1,
        cooperate_prob=0.7,
        strategy_schedule=None,
        **kwargs
    ):

        # ------------------------------------------------------------
        # Identity and strategy configuration
        # ------------------------------------------------------------
        self.id = id
        self.is_dummy = True
        self.strategy = strategy

        # Optional schedule:
        # Example:
        # {100: "Pavlov", 200: "Defector"}
        #
        # Enables regime-switching experiments.
        self.strategy_schedule = strategy_schedule or {}

        # ------------------------------------------------------------
        # Game structure
        # ------------------------------------------------------------
        self.game_matrix = game_matrix.to(torch.float)
        self.log_C = game_matrix

        self.num_agents = game_matrix.ndim
        self.num_actions = game_matrix.shape[0]
        self.num_states = num_states

        # ------------------------------------------------------------
        # Experimental controls
        # ------------------------------------------------------------

        # Noise:
        # probability that intended action flips.
        #
        # Useful for:
        # - Generous TFT
        # - Sensorimotor noise
        # - Robustness studies
        self.noise = noise

        # Mixed strategy cooperation probability.
        self.cooperate_prob = cooperate_prob

        # Pavlov reward threshold.
        self.reward_threshold = (
            reward_threshold
            if reward_threshold is not None
            else self.game_matrix.mean().item()
        )

        # ------------------------------------------------------------
        # Episode memory
        # ------------------------------------------------------------
        self.t = 0
        self.u = None

        self.last_opponent_action = None
        self.last_own_action = None
        self.last_payoff = None

        # ------------------------------------------------------------
        # Grim Trigger memory
        # ------------------------------------------------------------

        # Number of consecutive defections observed.
        self.defect_streak = 0

        # ThresholdGrim activates after this many defections.
        self.grim_threshold = grim_threshold

        # Once triggered, agent defects forever.
        self.grim_triggered = False

        # ------------------------------------------------------------
        # Hidden-state opponent
        # ------------------------------------------------------------

        # Ground-truth latent state.
        self.current_state = "friendly"

        # Hidden Markov transition matrix.
        #
        # Friendly -> mostly Friendly
        # Hostile  -> mostly Hostile
        #
        # This creates a genuine latent-state inference problem.
        self.hidden_transition = {
            "friendly": {"friendly": 0.9, "hostile": 0.1},
            "hostile": {"friendly": 0.1, "hostile": 0.9},
        }

        # ------------------------------------------------------------
        # Placeholder fields for simulator compatibility
        # ------------------------------------------------------------
        self.VFE = [0.0] * self.num_agents
        self.energy = [0.0] * self.num_agents
        self.entropy = [0.0] * self.num_agents
        self.accuracy = [0.0] * self.num_agents
        self.complexity = [0.0] * self.num_agents
        self.o_pred_record = torch.zeros((self.num_agents, self.num_actions))

        # --- Expected Free Energy ---
        self.EFE = torch.zeros(self.num_actions)
        self.EFE_terms = torch.zeros((1, 5))

        # --- Scalars ---
        self.gamma = 0.0
        self.learn_record = 0

        # --- Beliefs ---
        self.q_u = torch.zeros(self.num_actions)
        self.q_s = torch.ones((self.num_agents, self.num_states)) / self.num_states

        # --- Generative model placeholders ---
        self.A = torch.zeros((num_states, self.num_actions))
        self.B = torch.zeros((self.num_agents, self.num_actions, self.num_actions, self.num_actions))

        # --- BMR-related ---
        self.B_candidates = "None"
        self.B_model_weights = torch.zeros(self.num_agents, 1)
        self.delta_F = torch.zeros(1)

    def _apply_noise(self, action):
        """
        Inject action noise.

        Used to study robustness of inference under imperfect behaviour.
        """
        if random.random() < self.noise:
            return 1 - action
        return action

    def _current_strategy(self):
        """
        Check whether a strategy switch should occur.

        Useful for non-stationary environments.
        """
        if self.t in self.strategy_schedule:
            self.strategy = self.strategy_schedule[self.t]
        return self.strategy
    
    def set_log_C(self, game_matrix):
        self.log_C = game_matrix

    def select_action(self):
        """
        Generate action according to current strategy.
        """

        strategy = self._current_strategy()

        # Always cooperate.
        if strategy == "Cooperator":
            action = 0

        # Always defect.
        elif strategy == "Defector":
            action = 1

        # Tit-for-Tat:
        # Cooperate first, then copy opponent.
        elif strategy == "TFT":
            action = 0 if self.t == 0 or self.last_opponent_action is None else self.last_opponent_action

        # Probabilistic TFT.
        # Copies opponent most of the time.
        elif strategy == "StochasticTFT":
            if self.t == 0 or self.last_opponent_action is None:
                action = 0
            else:
                if self.last_opponent_action == 0:
                    action = 0 if random.random() < 0.9 else 1
                else:
                    action = 1 if random.random() < 0.9 else 0

        # Canonical Grim Trigger.
        elif strategy == "Grim":
            action = 1 if self.grim_triggered else 0

        # Forgiving version of Grim.
        elif strategy == "ThresholdGrim":
            action = 1 if self.grim_triggered else 0

        # Win-Stay Lose-Shift.
        elif strategy == "Pavlov":
            if self.t == 0 or self.last_payoff is None:
                action = 0
            else:
                win = self.last_payoff >= self.reward_threshold
                action = self.last_own_action if win else 1 - self.last_own_action

        # Memoryless mixed strategy.
        elif strategy == "Mixed":
            action = 0 if random.random() < self.cooperate_prob else 1

        # Hidden-state strategy.
        #
        # Friendly -> cooperate
        # Hostile  -> defect
        elif strategy == "HiddenState":
            action = 0 if self.current_state == "friendly" else 1

        else:
            raise ValueError(f"Unknown strategy: {strategy}")

        action = self._apply_noise(action)

        self.u = action
        self.q_u.zero_()
        self.q_u[action] = 1.0

        self.last_own_action = action
        self.t += 1

        return action

    def infer_state(self, o, u_all):
        """
        Update internal memory after observing the round outcome.

        Unlike Active Inference agents, no Bayesian inference occurs here.
        This function simply updates the information needed by each strategy.
        """

        opponent_id = 1 - self.id

        if self.t > 0:
            self.last_opponent_action = u_all[opponent_id]

        joint_action = tuple(torch.argmax(o_i).item() for o_i in o)
        self.last_payoff = self.log_C[joint_action].item()

        # Track consecutive defections.
        if self.last_opponent_action == 1:
            self.defect_streak += 1
        else:
            self.defect_streak = 0

        # Canonical Grim:
        # one observed defection triggers forever.
        if self.strategy == "Grim" and self.last_opponent_action == 1:
            self.grim_triggered = True

        # Threshold Grim:
        # trigger only after N consecutive defections.
        if (
            self.strategy == "ThresholdGrim"
            and self.defect_streak >= self.grim_threshold
        ):
            self.grim_triggered = True

        # Hidden-state Markov evolution.
        if self.strategy == "HiddenState":
            probs = self.hidden_transition[self.current_state]
            r = random.random()

            self.current_state = (
                "friendly"
                if r < probs["friendly"]
                else "hostile"
            )

        return self.q_s

    def get_ground_truth_state(self):
        """
        Return true latent state.

        Useful for:
        - state inference accuracy
        - calibration analysis
        - KL divergence evaluation
        """
        return self.current_state

    def learn(self):
        """
        Dummy agents do not learn.
        """
        self.learn_record = 0
